@identityServiceUrl = http://localhost:5201
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwidW5pcXVlX25hbWUiOiIxIiwianRpIjoiODcyMTcyZWYtZTZhYi00YmY1LTllM2ItZmY0MTA2MzUzZjMzIiwiaWF0IjoiMTU2MTU3OTc2MzQ3MSIsImF1ZCI6Im5leHREb29yLWlkZW50aXR5LXNlcnZpY2UiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsIm5iZiI6MTU2MTU5NDE2MywiZXhwIjoxNTYxNTk1OTYzLCJpc3MiOiJuZXh0RG9vci1pZGVudGl0eS1zZXJ2aWNlIn0.w98PzWzYtVEtKnDStQQygWjsl6Fzr8lK9FJvWPp7qZU
@refreshToken = AQAAAAEAACcQAAAAECAWIrJw6abl4zTCZ0JcUTxqwNbCQVeI8TJO00NuWZeJCKPuVdj18VfFceOFwLIw
# ================= IDENTITY SERVICE START ======================= #

### Sign up as admin
POST {{identityServiceUrl}}/sign-up
Content-Type: application/json

{
	"email": "nd-admin2@nextdoor.com",
	"password": "ndadmin321",
	"role": "admin"
}

### Sign in as admin
POST {{identityServiceUrl}}/sign-in
Content-Type: application/json

{
	"email": "nd-admin@nextdoor.com",
	"password": "ndadmin321"
}

### Change password
PUT {{identityServiceUrl}}/change-pwd
authorization: Bearer {{accessToken}}
Content-Type: application/json

{
	"userId": 1,
	"currentPassword": "ndadmin124",
	"newPassword": "ndadmin321"
}

## Token Management
### Renew Jwt Access Token
POST {{identityServiceUrl}}/access-tokens/{{refreshToken}}/renew
Content-Type: application/json

### Cancel Jwt Access Token
POST {{identityServiceUrl}}/access-tokens/cancel
authorization: Bearer {{accessToken}}
Content-Type: application/json

### Refresh Refresh Token
POST {{identityServiceUrl}}/refresh-tokens/{{refreshToken}}/revoke
authorization: Bearer {{accessToken}}
Content-Type: application/json
# Once authenticated, copy the obtained accessToken and update the @accessToken parameter above.

# ================= IDENTITY SERVICE END ======================= #